version: "3"

services:
    web:
        build: .
        container_name: webapp
        ports:
            - "5000:8000"
        links:
            - db
    
    db:
        container_name: mongo
        image: mongo:latest
        ports:
            - "27017:27017"