version: "3"

services:
    web:
        build: .
        image: docker-web-app_web:latest
        container_name: webapp
        ports:
            - "5000:8000"
        links:
            - db
    
    db:
        image: mongo:latest
        ports:
            - "27017:27017"