version: "3"

services:
    web:
        build: .
        image: docker-web-app_web:latest
        ports:
            - "80:8000"
        links:
            - db
        networks:
            - mynet
    
    db:
        image: mongo:latest
        ports:
            - "27017:27017"
        networks:
            - mynet

networks:
    mynet: