version: "3"

services:
    web:
        build: .
        image: evwalles/docker-web-app
        container_name: webapp
        ports:
            - "5000:8000"
        links:
            - db
        deploy:
            replicas: 2
    
    db:
        image: mongo:latest
        ports:
            - "27017:27017"
        deploy:
            placement:
                constraints: [node.role == manager]